# Generated by Django 3.2.3 on 2021-05-14 11:54

import api.models.employee.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_number', models.CharField(default=api.models.employee.models.Employee.uuid_pk, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED'), ('WIDOWED', 'WIDOWED')], max_length=10)),
                ('socials_security_number', models.CharField(max_length=10)),
                ('tin_number', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.CharField(max_length=100)),
                ('link_type', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
                ('email_type', models.CharField(max_length=100)),
                ('emp_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=100)),
                ('street_address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
